### ISSUE TITLE
Graceful handling of source files that contain both md and html

### ISSUE THREAD

**Issue by dvdlite** [danburzo/trimd#2]
Given a source file that contains both md and html, such as the attached file....

[sample.txt](https://github.com/danburzo/trimd/files/10786656/sample.txt)

When I try to convert to pure md via "trimd markdown sample.txt", the app escapes the existing markdown to render it literally rather than parse it.  Going the other direction, "trimd markup" correctly converts everything to html and leaves the existing html alone.

So, an easy workaround, humorously, is to convert the whole file to html, and then to md..

$ trimd markup sample.txt | trimd markdown --

This renders the intended pure md output.

A command line option (-i for "ignore existing markdown" perhaps?) would be cool for this scenario if it's trivial to code.  But as shown above, it's not necessary as there's an easy workaround.

Thank you for making a command line tool for this!  This allows me to script a tedious conversion project I've been working on!

**Comment by danburzo** [comment]
Ah, I see what you mean. In general, a mixture of HTML and Markdown is considered to be "Markdown with pockets of raw HTML embedded in it", and has an established processing model to mark it all up to HTML. To take it the other direction down to Markdown is a less common, but not unreasonable task. 

In a nutshell, the command needs to consider the input to be Markdown, but have it unwind the raw HTML bits.

**Comment by danburzo** [comment]
I've released `trimd remarkdown` as part of [`trimd@0.4.0`](https://github.com/danburzo/trimd/releases/tag/v0.4.0), this should cover the use-case you've mentioned, inasmuch as the sources are amenable to the `trimd markup | trimd markdown` workaround.

**Comment by dvdlite** [comment]
Works perfectly, thanks again!
